/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new account
         * @description Creates a new customer account and immediately opens a session. The response body includes `accessToken`; both tokens are also delivered as httpOnly cookies so that browser clients need not handle them manually.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterBody"];
                };
            };
            responses: {
                /** @description Account created and session opened */
                201: {
                    headers: {
                        /** @description Two httpOnly cookies are set: `access_token` (path /, maxAge = JWT_ACCESS_TTL) and `refresh_token` (path /api/v1/auth, expires = refreshExpiresAt). Both are Secure in production and SameSite=Lax. */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisterResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Email already registered */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate credentials and trigger OTP
         * @description Verifies email and password. On success, a 6-digit OTP is sent to the user's registered contact (email/SMS) with `purpose: login`. **No session is opened yet.** The client must complete the flow via `POST /auth/otp/complete-login`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginBody"];
                };
            };
            responses: {
                /** @description Credentials valid — OTP dispatched */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginPendingResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description OTP resend cooldown active */
                412: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate refresh token and obtain a new access token
         * @description Accepts the refresh token either from the `refresh_token` httpOnly cookie (browser clients) or from the request body (API / mobile clients). On success, new tokens are issued and the previous refresh token is revoked. Reuse of a revoked token terminates the entire token family.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: {
                    /** @description httpOnly refresh_token cookie set at login. When present, the request body is not needed. */
                    refresh_token?: string;
                };
            };
            /** @description Omit when using the refresh_token cookie. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshBody"];
                };
            };
            responses: {
                /** @description Tokens rotated */
                200: {
                    headers: {
                        /** @description Two httpOnly cookies are set: `access_token` (path /, maxAge = JWT_ACCESS_TTL) and `refresh_token` (path /api/v1/auth, expires = refreshExpiresAt). Both are Secure in production and SameSite=Lax. */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                /** @description Refresh token missing, invalid, or expired */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke refresh token family and clear session cookies
         * @description Revokes the entire refresh token family to prevent reuse. Cookies are cleared regardless of whether a token was found. Accepts the refresh token from the `refresh_token` cookie or the request body.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: {
                    /** @description httpOnly refresh_token cookie set at login. When present, the request body is not needed. */
                    refresh_token?: string;
                };
            };
            /** @description Omit when using the refresh_token cookie. */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LogoutBody"];
                };
            };
            responses: {
                /** @description Logged out — cookies cleared */
                204: {
                    headers: {
                        /** @description access_token and refresh_token cookies are cleared (Max-Age=0). */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request an OTP code
         * @description Generates a one-time password for the authenticated user and the requested purpose. The code is delivered out-of-band (email or SMS) — it is **never** returned in the response. Requests within the 60-second cooldown window return 412.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SendOtpBody"];
                };
            };
            responses: {
                /** @description OTP sent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SendOtpResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description User not found or inactive */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Resend cooldown active — try again after resendAllowedAt */
                412: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/complete-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete login by verifying the OTP
         * @description Second step of the login flow. Verifies the `login`-purpose OTP issued by `POST /auth/login`, marks it used, and opens a session. On success, access and refresh tokens are issued and set as httpOnly cookies.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteLoginBody"];
                };
            };
            responses: {
                /** @description OTP verified — session opened */
                200: {
                    headers: {
                        /** @description Two httpOnly cookies are set: `access_token` (path /, maxAge = JWT_ACCESS_TTL) and `refresh_token` (path /api/v1/auth, expires = refreshExpiresAt). Both are Secure in production and SameSite=Lax. */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid or expired OTP */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description User not found or inactive */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify an OTP code
         * @description Validates a one-time password. On success returns `{ verified: true }`. The OTP is immediately marked as used and cannot be replayed. This endpoint is public so it can be used during the password-reset flow before a session exists.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VerifyOtpBody"];
                };
            };
            responses: {
                /** @description OTP verified */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VerifyOtpResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid or expired OTP */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description User not found or inactive */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products (cursor-paginated) */
        get: {
            parameters: {
                query?: {
                    status?: "draft" | "active" | "archived";
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated product list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            data: components["schemas"]["Product"][];
                            meta: {
                                hasMore: boolean;
                                limit: number;
                                nextCursor?: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{idOrSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product by ID or slug */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    idOrSlug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product with variants */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            data: components["schemas"]["Product"];
                        };
                    };
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a variant to the cart (creates cart if needed) */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "x-guest-token"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddToCartBody"];
                };
            };
            responses: {
                /** @description Cart updated */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CartResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Variant not found or inactive */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Currency mismatch or missing cart owner */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/{cartId}/coupon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply a coupon code to a cart */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    cartId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApplyCouponBody"];
                };
            };
            responses: {
                /** @description Coupon applied */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            data: {
                                cart: components["schemas"]["Cart"];
                                /** @description Computed discount in minor units */
                                discountMinor: number;
                            };
                        };
                    };
                };
                /** @description Cart or coupon not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Coupon limit reached or conditions not met */
                412: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Place an order from a cart
         * @description Converts an active cart into an immutable order. Inventory is decremented atomically inside the same DB transaction. Requires the `Idempotency-Key` header — replay returns 200 with `Idempotent-Replayed: true`.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    "idempotency-key": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrderBody"];
                };
            };
            responses: {
                /** @description Idempotent replay of an already-created order */
                200: {
                    headers: {
                        "Idempotent-Replayed"?: "true";
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            data: components["schemas"]["Order"];
                        };
                    };
                };
                /** @description Order created */
                201: {
                    headers: {
                        /** @description false on first creation */
                        "Idempotent-Replayed"?: "false";
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {boolean} */
                            success: true;
                            data: components["schemas"]["Order"];
                        };
                    };
                };
                /** @description Validation error or missing Idempotency-Key */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authentication required */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Cart not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Cart already converted, currency mismatch, or idempotency-key conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Cart empty, variant unavailable, or insufficient stock */
                412: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                user: {
                    /** Format: uuid */
                    id: string;
                    /** Format: email */
                    email: string;
                    fullName: string | null;
                    /** @enum {string} */
                    role: "customer" | "staff" | "admin";
                    isActive: boolean;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                };
                /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                accessToken: string;
                /**
                 * Format: date-time
                 * @example 2026-06-06T12:00:00.000Z
                 */
                refreshExpiresAt: string;
            };
        };
        RegisterBody: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example s3cur3p@ssw0rd */
            password: string;
            /** @example Jane Doe */
            fullName?: string;
        };
        LoginPendingResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                /**
                 * @description Always true. A 6-digit OTP has been sent to the user's registered contact.
                 * @enum {boolean}
                 */
                requiresOtp: true;
                /**
                 * Format: uuid
                 * @description The user ID required to complete the login via POST /auth/otp/complete-login.
                 * @example 01910000-0000-7000-0000-000000000001
                 */
                userId: string;
                /**
                 * Format: date-time
                 * @description Earliest time the OTP may be resent (60-second cooldown).
                 * @example 2026-05-07T12:01:00.000Z
                 */
                resendAllowedAt: string;
            };
        };
        LoginBody: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example s3cur3p@ssw0rd */
            password: string;
        };
        SessionResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                /**
                 * @description Short-lived JWT (default 15 min). Also delivered via the access_token httpOnly cookie.
                 * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                 */
                accessToken: string;
                /**
                 * Format: date-time
                 * @example 2026-06-06T12:00:00.000Z
                 */
                refreshExpiresAt: string;
            };
        };
        RefreshBody: {
            /** @example <opaque-refresh-token> */
            refreshToken?: string;
        };
        LogoutBody: {
            /** @example <opaque-refresh-token> */
            refreshToken?: string;
        };
        SendOtpResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                /**
                 * Format: date-time
                 * @description When the OTP expires (10 minutes from generation).
                 * @example 2026-05-07T12:10:00.000Z
                 */
                expiresAt: string;
                /**
                 * Format: date-time
                 * @description Earliest time a new OTP may be requested (60-second cooldown).
                 * @example 2026-05-07T12:01:00.000Z
                 */
                resendAllowedAt: string;
            };
        };
        SendOtpBody: {
            /**
             * @description `email_verification` — confirm account email after registration. `login` — passwordless login flow. `password_reset` — step in the forgot-password flow.
             * @example email_verification
             * @enum {string}
             */
            purpose: "email_verification" | "login" | "password_reset";
        };
        CompleteLoginBody: {
            /**
             * Format: uuid
             * @example 01910000-0000-7000-0000-000000000001
             */
            userId: string;
            /** @example 482916 */
            code: string;
        };
        VerifyOtpResponse: {
            /** @enum {boolean} */
            success: true;
            data: {
                /** @enum {boolean} */
                verified: true;
            };
        };
        VerifyOtpBody: {
            /**
             * Format: uuid
             * @example 01910000-0000-7000-0000-000000000001
             */
            userId: string;
            /**
             * @example email_verification
             * @enum {string}
             */
            purpose: "email_verification" | "login" | "password_reset";
            /** @example 482916 */
            code: string;
        };
        ProductVariant: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            productId: string;
            sku: string;
            name: string;
            /** @description Price in minor units (cents) */
            priceMinor: number;
            /** @example USD */
            currency: string;
            options: {
                [key: string]: string;
            };
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Product: {
            /** Format: uuid */
            id: string;
            sku: string;
            slug: string;
            title: string;
            description: string | null;
            /** @enum {string} */
            status: "draft" | "active" | "archived";
            attributes: {
                [key: string]: string | number | boolean;
            };
            variants: components["schemas"]["ProductVariant"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CartItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            cartId: string;
            /** Format: uuid */
            variantId: string;
            quantity: number;
            /** @description Unit price in minor units (cents) */
            unitPriceMinor: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Cart: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string | null;
            guestToken: string | null;
            /** @example USD */
            currency: string;
            /** @enum {string} */
            status: "active" | "converted" | "abandoned";
            couponCode: string | null;
            metadata: {
                [key: string]: unknown;
            };
            items: components["schemas"]["CartItem"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CartResponse: {
            /** @enum {boolean} */
            success: true;
            data: components["schemas"]["Cart"];
        };
        AddToCartBody: {
            /**
             * Format: uuid
             * @example 018e8f3a-0000-7000-8000-000000000001
             */
            variantId: string;
            /** @example 2 */
            quantity: number;
            /**
             * @description Required when not authenticated. Supply either this or a Bearer token.
             * @example guest-abc123xyz
             */
            guestToken?: string;
        };
        ApplyCouponBody: {
            /** @example SUMMER20 */
            code: string;
        };
        OrderItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            orderId: string;
            /** Format: uuid */
            variantId: string;
            sku: string;
            name: string;
            quantity: number;
            unitPriceMinor: number;
            totalMinor: number;
        };
        Order: {
            /** Format: uuid */
            id: string;
            /** @example ORD-LK3MN9-018E8F */
            orderNumber: string;
            /** Format: uuid */
            userId: string | null;
            /** @enum {string} */
            status: "pending_payment" | "paid" | "processing" | "shipped" | "delivered" | "cancelled" | "refunded";
            /** @example USD */
            currency: string;
            subtotalMinor: number;
            discountMinor: number;
            taxMinor: number;
            shippingMinor: number;
            /** @description Final charged amount in minor units */
            totalMinor: number;
            couponCode: string | null;
            shippingAddress: {
                [key: string]: string;
            } | null;
            billingAddress: {
                [key: string]: string;
            } | null;
            metadata: {
                [key: string]: unknown;
            };
            items: components["schemas"]["OrderItem"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateOrderBody: {
            /**
             * Format: uuid
             * @example 018e8f3a-0000-7000-8000-000000000002
             */
            cartId: string;
            /**
             * @example {
             *       "street": "123 Main St",
             *       "city": "New York",
             *       "country": "US",
             *       "zip": "10001"
             *     }
             */
            shippingAddress?: {
                [key: string]: string;
            };
            billingAddress?: {
                [key: string]: string;
            };
            /**
             * @description Tax in minor units
             * @default 0
             * @example 800
             */
            taxMinor: number;
            /**
             * @description Shipping in minor units
             * @default 0
             * @example 500
             */
            shippingMinor: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaRegisterResponse = components['schemas']['RegisterResponse'];
export type SchemaRegisterBody = components['schemas']['RegisterBody'];
export type SchemaLoginPendingResponse = components['schemas']['LoginPendingResponse'];
export type SchemaLoginBody = components['schemas']['LoginBody'];
export type SchemaSessionResponse = components['schemas']['SessionResponse'];
export type SchemaRefreshBody = components['schemas']['RefreshBody'];
export type SchemaLogoutBody = components['schemas']['LogoutBody'];
export type SchemaSendOtpResponse = components['schemas']['SendOtpResponse'];
export type SchemaSendOtpBody = components['schemas']['SendOtpBody'];
export type SchemaCompleteLoginBody = components['schemas']['CompleteLoginBody'];
export type SchemaVerifyOtpResponse = components['schemas']['VerifyOtpResponse'];
export type SchemaVerifyOtpBody = components['schemas']['VerifyOtpBody'];
export type SchemaProductVariant = components['schemas']['ProductVariant'];
export type SchemaProduct = components['schemas']['Product'];
export type SchemaCartItem = components['schemas']['CartItem'];
export type SchemaCart = components['schemas']['Cart'];
export type SchemaCartResponse = components['schemas']['CartResponse'];
export type SchemaAddToCartBody = components['schemas']['AddToCartBody'];
export type SchemaApplyCouponBody = components['schemas']['ApplyCouponBody'];
export type SchemaOrderItem = components['schemas']['OrderItem'];
export type SchemaOrder = components['schemas']['Order'];
export type SchemaCreateOrderBody = components['schemas']['CreateOrderBody'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
