/**
 * This file was auto-generated by scripts/generate-api-types.ts.
 * Do not make direct changes to the file.
 */

import type { paths } from "../schema.d.ts";

export type ApiPath = keyof paths & `/${string}`;
export type ApiEndpoint = `/${string}`;

