/**
 * This file was auto-generated by scripts/generate-api-types.ts.
 * Do not make direct changes to the file.
 */

export type SuccessResponse<T> = T extends { responses: infer Responses }
  ? Responses extends Record<number, unknown>
    ? 200 extends keyof Responses
      ? Responses[200] extends { content: { "application/json": infer Body } }
        ? Body
        : never
      : 201 extends keyof Responses
        ? Responses[201] extends { content: { "application/json": infer Body } }
          ? Body
          : never
        : never
    : never
  : never;

