/**
 * This file was auto-generated by scripts/generate-api-types.ts.
 * Do not make direct changes to the file.
 */

import { apiClient } from "../client";
import { ApiError } from "../envelope";
import type { FetchOptions } from "openapi-fetch";
import type { paths } from "../schema.d.ts";
import type { RequestOptions } from "../shared/types";

import { API_AUTH_PATHS } from "./endpoints";

export async function login(
  ...[options]: RequestOptions<FetchOptions<paths[typeof API_AUTH_PATHS.AUTH_LOGIN]["post"]>>
) {
  const { data, error, response } = await apiClient.POST(API_AUTH_PATHS.AUTH_LOGIN, options as FetchOptions<paths[typeof API_AUTH_PATHS.AUTH_LOGIN]["post"]>);
  const status = response.status;
  if (error) {
    const errObj = error as unknown as { error?: { message?: string }; message?: string };
    const msg = errObj?.error?.message ?? errObj?.message ?? "API Error";
    throw new ApiError(msg, status, errObj);
  }
  return data;
}

export async function logout(
  ...[options]: RequestOptions<FetchOptions<paths[typeof API_AUTH_PATHS.AUTH_LOGOUT]["post"]>>
) {
  const { data, error, response } = await apiClient.POST(API_AUTH_PATHS.AUTH_LOGOUT, options as FetchOptions<paths[typeof API_AUTH_PATHS.AUTH_LOGOUT]["post"]>);
  const status = response.status;
  if (error) {
    const errObj = error as unknown as { error?: { message?: string }; message?: string };
    const msg = errObj?.error?.message ?? errObj?.message ?? "API Error";
    throw new ApiError(msg, status, errObj);
  }
  return data;
}

export async function sendOtp(
  ...[options]: RequestOptions<FetchOptions<paths[typeof API_AUTH_PATHS.AUTH_OTP_SEND]["post"]>>
) {
  const { data, error, response } = await apiClient.POST(API_AUTH_PATHS.AUTH_OTP_SEND, options as FetchOptions<paths[typeof API_AUTH_PATHS.AUTH_OTP_SEND]["post"]>);
  const status = response.status;
  if (error) {
    const errObj = error as unknown as { error?: { message?: string }; message?: string };
    const msg = errObj?.error?.message ?? errObj?.message ?? "API Error";
    throw new ApiError(msg, status, errObj);
  }
  return data;
}

export async function verifyOtp(
  ...[options]: RequestOptions<FetchOptions<paths[typeof API_AUTH_PATHS.AUTH_OTP_VERIFY]["post"]>>
) {
  const { data, error, response } = await apiClient.POST(API_AUTH_PATHS.AUTH_OTP_VERIFY, options as FetchOptions<paths[typeof API_AUTH_PATHS.AUTH_OTP_VERIFY]["post"]>);
  const status = response.status;
  if (error) {
    const errObj = error as unknown as { error?: { message?: string }; message?: string };
    const msg = errObj?.error?.message ?? errObj?.message ?? "API Error";
    throw new ApiError(msg, status, errObj);
  }
  return data;
}

export async function refresh(
  ...[options]: RequestOptions<FetchOptions<paths[typeof API_AUTH_PATHS.AUTH_REFRESH]["post"]>>
) {
  const { data, error, response } = await apiClient.POST(API_AUTH_PATHS.AUTH_REFRESH, options as FetchOptions<paths[typeof API_AUTH_PATHS.AUTH_REFRESH]["post"]>);
  const status = response.status;
  if (error) {
    const errObj = error as unknown as { error?: { message?: string }; message?: string };
    const msg = errObj?.error?.message ?? errObj?.message ?? "API Error";
    throw new ApiError(msg, status, errObj);
  }
  return data;
}

export async function register(
  ...[options]: RequestOptions<FetchOptions<paths[typeof API_AUTH_PATHS.AUTH_REGISTER]["post"]>>
) {
  const { data, error, response } = await apiClient.POST(API_AUTH_PATHS.AUTH_REGISTER, options as FetchOptions<paths[typeof API_AUTH_PATHS.AUTH_REGISTER]["post"]>);
  const status = response.status;
  if (error) {
    const errObj = error as unknown as { error?: { message?: string }; message?: string };
    const msg = errObj?.error?.message ?? errObj?.message ?? "API Error";
    throw new ApiError(msg, status, errObj);
  }
  return data;
}
