/**
 * This file was auto-generated by scripts/generate-api-types.ts.
 * Do not make direct changes to the file.
 */

import type { components, paths } from "../schema.d.ts";
import type { SuccessResponse } from "../shared/types";

export type SchemaCompleteLoginBody = components["schemas"]["CompleteLoginBody"];
export type SchemaLoginBody = components["schemas"]["LoginBody"];
export type SchemaLoginPendingResponse = components["schemas"]["LoginPendingResponse"];
export type SchemaLogoutBody = components["schemas"]["LogoutBody"];
export type SchemaRefreshBody = components["schemas"]["RefreshBody"];
export type SchemaRegisterBody = components["schemas"]["RegisterBody"];
export type SchemaRegisterResponse = components["schemas"]["RegisterResponse"];
export type SchemaSendOtpBody = components["schemas"]["SendOtpBody"];
export type SchemaSendOtpResponse = components["schemas"]["SendOtpResponse"];
export type SchemaSessionResponse = components["schemas"]["SessionResponse"];
export type SchemaVerifyOtpBody = components["schemas"]["VerifyOtpBody"];
export type SchemaVerifyOtpResponse = components["schemas"]["VerifyOtpResponse"];

export type AuthLoginPost = NonNullable<paths["/auth/login"]["post"]>;
export type AuthLoginPostQuery = NonNullable<AuthLoginPost["parameters"]["query"]>;
export type AuthLoginPostResponse = SuccessResponse<AuthLoginPost>;
export type AuthLogoutPost = NonNullable<paths["/auth/logout"]["post"]>;
export type AuthLogoutPostQuery = NonNullable<AuthLogoutPost["parameters"]["query"]>;
export type AuthLogoutPostResponse = SuccessResponse<AuthLogoutPost>;
export type AuthOtpCompleteLoginPost = NonNullable<paths["/auth/otp/complete-login"]["post"]>;
export type AuthOtpCompleteLoginPostQuery = NonNullable<AuthOtpCompleteLoginPost["parameters"]["query"]>;
export type AuthOtpCompleteLoginPostResponse = SuccessResponse<AuthOtpCompleteLoginPost>;
export type AuthOtpSendPost = NonNullable<paths["/auth/otp/send"]["post"]>;
export type AuthOtpSendPostQuery = NonNullable<AuthOtpSendPost["parameters"]["query"]>;
export type AuthOtpSendPostResponse = SuccessResponse<AuthOtpSendPost>;
export type AuthOtpVerifyPost = NonNullable<paths["/auth/otp/verify"]["post"]>;
export type AuthOtpVerifyPostQuery = NonNullable<AuthOtpVerifyPost["parameters"]["query"]>;
export type AuthOtpVerifyPostResponse = SuccessResponse<AuthOtpVerifyPost>;
export type AuthRefreshPost = NonNullable<paths["/auth/refresh"]["post"]>;
export type AuthRefreshPostQuery = NonNullable<AuthRefreshPost["parameters"]["query"]>;
export type AuthRefreshPostResponse = SuccessResponse<AuthRefreshPost>;
export type AuthRegisterPost = NonNullable<paths["/auth/register"]["post"]>;
export type AuthRegisterPostQuery = NonNullable<AuthRegisterPost["parameters"]["query"]>;
export type AuthRegisterPostResponse = SuccessResponse<AuthRegisterPost>;
