/**
 * This file was auto-generated by scripts/generate-api-types.ts.
 * Do not make direct changes to the file.
 */

import type { ApiPath } from "../shared/endpoints";

export const API_ORDERS_PATHS = {
  ORDERS: "/orders",
} as const satisfies Record<string, ApiPath>;

export const API_ORDERS_ENDPOINTS = {
  ORDERS: API_ORDERS_PATHS.ORDERS,
} as const;
