/**
 * This file was auto-generated by scripts/generate-api-types.ts.
 * Do not make direct changes to the file.
 */

import type { components, paths } from "../schema.d.ts";
import type { SuccessResponse } from "../shared/types";

export type SchemaCreateOrderBody = components["schemas"]["CreateOrderBody"];
export type SchemaOrder = components["schemas"]["Order"];
export type SchemaOrderItem = components["schemas"]["OrderItem"];

export type OrdersPost = NonNullable<paths["/orders"]["post"]>;
export type OrdersPostQuery = NonNullable<OrdersPost["parameters"]["query"]>;
export type OrdersPostResponse = SuccessResponse<OrdersPost>;
