/**
 * This file was auto-generated by scripts/generate-api-types.ts.
 * Do not make direct changes to the file.
 */

import type { ApiEndpoint, ApiPath } from "../shared/endpoints";

export const API_PRODUCTS_PATHS = {
  PRODUCTS: "/products",
  PRODUCTS_ID_OR_SLUG: "/products/{idOrSlug}",
} as const satisfies Record<string, ApiPath>;

export const API_PRODUCTS_ENDPOINTS = {
  PRODUCTS: API_PRODUCTS_PATHS.PRODUCTS,
  PRODUCTS_ID_OR_SLUG: (params: { idOrSlug: string }) => `/products/${encodeURIComponent(params.idOrSlug)}` as ApiEndpoint,
} as const;
