/**
 * This file was auto-generated by scripts/generate-api-types.ts.
 * Do not make direct changes to the file.
 */

import { apiClient } from "../client";
import { ApiError } from "../envelope";
import type { FetchOptions } from "openapi-fetch";
import type { paths } from "../schema.d.ts";
import type { RequestOptions } from "../shared/types";

import { API_PRODUCTS_PATHS } from "./endpoints";

export async function getProducts(
  ...[options]: RequestOptions<FetchOptions<paths[typeof API_PRODUCTS_PATHS.PRODUCTS]["get"]>>
) {
  const { data, error, response } = await apiClient.GET(API_PRODUCTS_PATHS.PRODUCTS, options as FetchOptions<paths[typeof API_PRODUCTS_PATHS.PRODUCTS]["get"]>);
  const status = response.status;
  if (error) {
    const errObj = error as unknown as { error?: { message?: string }; message?: string };
    const msg = errObj?.error?.message ?? errObj?.message ?? "API Error";
    throw new ApiError(msg, status, errObj);
  }
  return data;
}

export async function getProduct(
  ...[options]: RequestOptions<FetchOptions<paths[typeof API_PRODUCTS_PATHS.PRODUCTS_ID_OR_SLUG]["get"]>>
) {
  const { data, error, response } = await apiClient.GET(API_PRODUCTS_PATHS.PRODUCTS_ID_OR_SLUG, options as FetchOptions<paths[typeof API_PRODUCTS_PATHS.PRODUCTS_ID_OR_SLUG]["get"]>);
  const status = response.status;
  if (error) {
    const errObj = error as unknown as { error?: { message?: string }; message?: string };
    const msg = errObj?.error?.message ?? errObj?.message ?? "API Error";
    throw new ApiError(msg, status, errObj);
  }
  return data;
}
