/**
 * This file was auto-generated by scripts/generate-api-types.ts.
 * Do not make direct changes to the file.
 */

import type { components, paths } from "../schema.d.ts";
import type { SuccessResponse } from "../shared/types";

export type SchemaProduct = components["schemas"]["Product"];
export type SchemaProductVariant = components["schemas"]["ProductVariant"];

export type ProductsGet = NonNullable<paths["/products"]["get"]>;
export type ProductsGetQuery = NonNullable<ProductsGet["parameters"]["query"]>;
export type ProductsGetResponse = SuccessResponse<ProductsGet>;
export type ProductsIdOrSlugGet = NonNullable<paths["/products/{idOrSlug}"]["get"]>;
export type ProductsIdOrSlugGetQuery = NonNullable<ProductsIdOrSlugGet["parameters"]["query"]>;
export type ProductsIdOrSlugGetResponse = SuccessResponse<ProductsIdOrSlugGet>;
