/**
 * This file was auto-generated by scripts/generate-api-types.ts.
 * Do not make direct changes to the file.
 */

import type { ApiEndpoint, ApiPath } from "../shared/endpoints";

export const API_CART_PATHS = {
  CART_ITEMS: "/cart/items",
  CART_CART_ID_COUPON: "/cart/{cartId}/coupon",
} as const satisfies Record<string, ApiPath>;

export const API_CART_ENDPOINTS = {
  CART_ITEMS: API_CART_PATHS.CART_ITEMS,
  CART_CART_ID_COUPON: (params: { cartId: string }) => `/cart/${encodeURIComponent(params.cartId)}/coupon` as ApiEndpoint,
} as const;
