/**
 * This file was auto-generated by scripts/generate-api-types.ts.
 * Do not make direct changes to the file.
 */

import { apiClient } from "../client";
import { ApiError } from "../envelope";
import type { FetchOptions } from "openapi-fetch";
import type { paths } from "../schema.d.ts";
import type { RequestOptions } from "../shared/types";

import { API_CART_PATHS } from "./endpoints";

export async function addCartItem(
  ...[options]: RequestOptions<FetchOptions<paths[typeof API_CART_PATHS.CART_ITEMS]["post"]>>
) {
  const { data, error, response } = await apiClient.POST(API_CART_PATHS.CART_ITEMS, options as FetchOptions<paths[typeof API_CART_PATHS.CART_ITEMS]["post"]>);
  const status = response.status;
  if (error) {
    const errObj = error as unknown as { error?: { message?: string }; message?: string };
    const msg = errObj?.error?.message ?? errObj?.message ?? "API Error";
    throw new ApiError(msg, status, errObj);
  }
  return data;
}

export async function applyCoupon(
  ...[options]: RequestOptions<FetchOptions<paths[typeof API_CART_PATHS.CART_CART_ID_COUPON]["post"]>>
) {
  const { data, error, response } = await apiClient.POST(API_CART_PATHS.CART_CART_ID_COUPON, options as FetchOptions<paths[typeof API_CART_PATHS.CART_CART_ID_COUPON]["post"]>);
  const status = response.status;
  if (error) {
    const errObj = error as unknown as { error?: { message?: string }; message?: string };
    const msg = errObj?.error?.message ?? errObj?.message ?? "API Error";
    throw new ApiError(msg, status, errObj);
  }
  return data;
}
