/**
 * This file was auto-generated by scripts/generate-api-types.ts.
 * Do not make direct changes to the file.
 */

import type { components, paths } from "../schema.d.ts";
import type { SuccessResponse } from "../shared/types";

export type SchemaAddToCartBody = components["schemas"]["AddToCartBody"];
export type SchemaApplyCouponBody = components["schemas"]["ApplyCouponBody"];
export type SchemaCart = components["schemas"]["Cart"];
export type SchemaCartItem = components["schemas"]["CartItem"];
export type SchemaCartResponse = components["schemas"]["CartResponse"];

export type CartItemsPost = NonNullable<paths["/cart/items"]["post"]>;
export type CartItemsPostQuery = NonNullable<CartItemsPost["parameters"]["query"]>;
export type CartItemsPostResponse = SuccessResponse<CartItemsPost>;
export type CartCartIdCouponPost = NonNullable<paths["/cart/{cartId}/coupon"]["post"]>;
export type CartCartIdCouponPostQuery = NonNullable<CartCartIdCouponPost["parameters"]["query"]>;
export type CartCartIdCouponPostResponse = SuccessResponse<CartCartIdCouponPost>;
