import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const OUTPUT = path.resolve(ROOT, "src/lib/api/schema.d.ts");
const API_DIR = path.resolve(ROOT, "src/lib/api");
const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3000";
const OPENAPI_URL = `${API_URL}/api/openapi.json`;
const tmpSpec = path.resolve(ROOT, "node_modules/.cache/openapi-spec.json");

const skipIfCached = process.argv.includes("--skip-if-cached");

console.log(`[codegen] Fetching OpenAPI spec from ${OPENAPI_URL} …`);

let specJson: string;
try {
  const res = await fetch(OPENAPI_URL);
  if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText}`);
  specJson = await res.text();
} catch (err) {
  console.error(`[codegen] ERROR: Could not reach the API at ${OPENAPI_URL}`);
  console.error(`         Make sure the backend is running: cd /var/projects/personal/backend/node/tte-ecommerce-api && pnpm dev`);
  console.error(err);
  if (skipIfCached && fs.existsSync(OUTPUT)) {
    console.warn("[codegen] WARNING: Using stale cached schema.d.ts (API unreachable).");
    process.exit(0);
  }
  process.exit(1);
}

if (
  skipIfCached &&
  fs.existsSync(OUTPUT) &&
  fs.existsSync(path.resolve(API_DIR, "shared/index.ts")) &&
  fs.existsSync(tmpSpec) &&
  fs.readFileSync(tmpSpec, "utf8") === specJson
) {
  console.log("[codegen] OpenAPI spec is unchanged, skipping.");
  process.exit(0);
}

fs.mkdirSync(path.dirname(tmpSpec), { recursive: true });
fs.writeFileSync(tmpSpec, specJson);

console.log("[codegen] Running openapi-typescript …");

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });

try {
  execSync(
    `pnpm exec openapi-typescript "${tmpSpec}" --output "${OUTPUT}" --root-types`,
    { cwd: ROOT, stdio: "inherit" },
  );
} catch {
  console.error("[codegen] openapi-typescript failed.");
  process.exit(1);
}

generateApiModules(JSON.parse(specJson) as OpenApiSpec);

console.log(`[codegen] Done → ${path.relative(ROOT, OUTPUT)}, ${path.relative(ROOT, API_DIR)}/*`);

interface OpenApiSpec {
  paths?: Record<string, Record<string, unknown>>;
  components?: {
    schemas?: Record<string, unknown>;
  };
}

interface PathEntry {
  apiPath: string;
  moduleName: string;
  name: string;
  params: string[];
  methods: string[];
}

function generateApiModules(spec: OpenApiSpec) {
  const pathEntries = getPathEntries(spec);
  const schemaModules = groupBy(
    Object.keys(spec.components?.schemas ?? {})
      .sort()
      .map((schemaName) => ({ schemaName, moduleName: getSchemaModuleName(schemaName) })),
    (entry) => entry.moduleName,
  );
  const pathModules = groupBy(pathEntries, (entry) => entry.moduleName);
  
  const moduleNames = new Set([...schemaModules.keys(), ...pathModules.keys(), "shared"]);

  // Clean up existing module directories
  if (fs.existsSync(API_DIR)) {
    const dirs = fs.readdirSync(API_DIR, { withFileTypes: true });
    for (const dir of dirs) {
      if (dir.isDirectory()) {
        if (dir.name === "types" || dir.name === "endpoints") {
          fs.rmSync(path.resolve(API_DIR, dir.name), { recursive: true, force: true });
          continue;
        }
        const endpointsPath = path.resolve(API_DIR, dir.name, "endpoints.ts");
        const typesPath = path.resolve(API_DIR, dir.name, "types.ts");
        if (fs.existsSync(endpointsPath) || fs.existsSync(typesPath)) {
          fs.rmSync(path.resolve(API_DIR, dir.name), { recursive: true, force: true });
        }
      }
    }
  }

  for (const moduleName of [...moduleNames].sort()) {
    const dir = path.resolve(API_DIR, moduleName);
    fs.mkdirSync(dir, { recursive: true });

    const entries = pathModules.get(moduleName) ?? [];
    
    // --- Generate endpoints.ts ---
    let endContent = `/**\n * This file was auto-generated by scripts/generate-api-types.ts.\n * Do not make direct changes to the file.\n */\n\n`;

    if (moduleName === "shared") {
      endContent += `import type { paths } from "../schema.d.ts";\n\n`;
      endContent += `export type ApiPath = keyof paths & \`/\${string}\`;\n`;
      endContent += `export type ApiEndpoint = \`/\${string}\`;\n\n`;
    } else {
      const needsApiEndpoint = entries.some((e) => e.params.length > 0);
      if (needsApiEndpoint) {
        endContent += `import type { ApiEndpoint, ApiPath } from "../shared/endpoints";\n\n`;
      } else {
        endContent += `import type { ApiPath } from "../shared/endpoints";\n\n`;
      }
    }

    if (entries.length > 0) {
      const constantPrefix = `API_${moduleName.toUpperCase().replace(/[^A-Z0-9_]/g, "_")}`;
      const pathConstants = entries.map(({ apiPath, name }) => `  ${name}: "${apiPath}",`).join("\n");
      const endpointConstants = entries
        .map(({ apiPath, name, params }) => {
          if (params.length === 0) return `  ${name}: ${constantPrefix}_PATHS.${name},`;

          const paramsType = params.map((param) => `${param}: string`).join("; ");
          const template = apiPath.replace(/\{([^}]+)\}/g, (_, param: string) => `\${encodeURIComponent(params.${param})}`);
          return `  ${name}: (params: { ${paramsType} }) => \`${template}\` as ApiEndpoint,`;
        })
        .join("\n");

      endContent += `export const ${constantPrefix}_PATHS = {
${pathConstants}
} as const satisfies Record<string, ApiPath>;

export const ${constantPrefix}_ENDPOINTS = {
${endpointConstants}
} as const;
`;
    }
    fs.writeFileSync(path.resolve(dir, "endpoints.ts"), endContent);

    // --- Generate types.ts ---
    let typeContent = `/**\n * This file was auto-generated by scripts/generate-api-types.ts.\n * Do not make direct changes to the file.\n */\n\n`;

    if (moduleName === "shared") {
      typeContent += `export type SuccessResponse<T> = T extends { responses: infer Responses }
  ? Responses extends Record<number, unknown>
    ? 200 extends keyof Responses
      ? Responses[200] extends { content: { "application/json": infer Body } }
        ? Body
        : never
      : 201 extends keyof Responses
        ? Responses[201] extends { content: { "application/json": infer Body } }
          ? Body
          : never
        : never
    : never
  : never;

export type RequestOptions<T> = {} extends T ? [options?: T] : [options: T];\n\n`;
    }

    const schemaAliases = (schemaModules.get(moduleName) ?? [])
      .map(({ schemaName }) => `export type Schema${schemaName} = components["schemas"]["${schemaName}"];`)
      .join("\n");
      
    const operationAliases = entries
      .flatMap((entry) =>
        entry.methods.map((method) => {
          const operationName = toPascalCase(`${entry.name}_${method}`);
          return `export type ${operationName} = NonNullable<paths["${entry.apiPath}"]["${method}"]>;\nexport type ${operationName}Query = NonNullable<${operationName}["parameters"]["query"]>;\nexport type ${operationName}Response = SuccessResponse<${operationName}>;`;
        }),
      )
      .join("\n");

    if (schemaAliases || operationAliases) {
      typeContent += `import type { components, paths } from "../schema.d.ts";\n`;
      if (moduleName !== "shared" && operationAliases) {
        typeContent += `import type { SuccessResponse } from "../shared/types";\n`;
      }
      typeContent += `\n`;
      
      if (schemaAliases) {
         typeContent += schemaAliases + `\n`;
      }
      if (schemaAliases && operationAliases) {
         typeContent += `\n`;
      }
      if (operationAliases) {
         typeContent += operationAliases + `\n`;
      }
    }

    fs.writeFileSync(path.resolve(dir, "types.ts"), typeContent);

    // --- Generate requests.ts ---
    if (entries.length > 0) {
      let reqContent = `/**\n * This file was auto-generated by scripts/generate-api-types.ts.\n * Do not make direct changes to the file.\n */\n\n`;
      reqContent += `import { apiClient } from "../client";\n`;
      reqContent += `import { ApiError } from "../envelope";\n`;
      reqContent += `import type { FetchOptions } from "openapi-fetch";\n`;
      reqContent += `import type { paths } from "../schema.d.ts";\n`;
      reqContent += `import type { RequestOptions } from "../shared/types";\n\n`;

      reqContent += `import { API_${moduleName.toUpperCase()}_PATHS } from "./endpoints";\n\n`;

      const OPERATION_NAMES: Record<string, Record<string, string>> = {
        "/auth/register": { post: "register" },
        "/auth/login": { post: "login" },
        "/auth/refresh": { post: "refresh" },
        "/auth/logout": { post: "logout" },
        "/auth/otp/send": { post: "sendOtp" },
        "/auth/otp/verify": { post: "verifyOtp" },
        "/products": { get: "getProducts" },
        "/products/{idOrSlug}": { get: "getProduct" },
        "/cart/items": { post: "addCartItem" },
        "/cart/{cartId}/coupon": { post: "applyCoupon" },
        "/orders": { post: "createOrder" },
      };

      const reqFunctions = entries.flatMap((entry) => 
        entry.methods.map((method) => {
          const defaultPascal = toPascalCase(`${entry.name}_${method}`);
          const defaultCamel = defaultPascal.charAt(0).toLowerCase() + defaultPascal.slice(1);
          const fnName = OPERATION_NAMES[entry.apiPath]?.[method] || defaultCamel;
          const pathConst = `API_${moduleName.toUpperCase()}_PATHS.${entry.name}`;
          
          return `export async function ${fnName}(
  ...[options]: RequestOptions<FetchOptions<paths[typeof ${pathConst}]["${method}"]>>
) {
  const { data, error, response } = await apiClient.${method.toUpperCase()}(${pathConst}, options as FetchOptions<paths[typeof ${pathConst}]["${method}"]>);
  const status = response.status;
  if (error) {
    const errObj = error as unknown as { error?: { message?: string }; message?: string };
    const msg = errObj?.error?.message ?? errObj?.message ?? "API Error";
    throw new ApiError(msg, status, errObj);
  }
  return data;
}`;
        })
      ).join("\n\n");

      reqContent += reqFunctions + "\n";
      fs.writeFileSync(path.resolve(dir, "requests.ts"), reqContent);
    }

    // --- Generate index.ts ---
    let indexContent = `/**\n * This file was auto-generated by scripts/generate-api-types.ts.\n * Do not make direct changes to the file.\n */\n\n`;
    indexContent += `export * from "./endpoints";\n`;
    indexContent += `export * from "./types";\n`;
    if (entries.length > 0) {
      indexContent += `export * from "./requests";\n`;
    }
    fs.writeFileSync(path.resolve(dir, "index.ts"), indexContent);
  }
}

function getPathEntries(spec: OpenApiSpec): PathEntry[] {
  const endpointNames = new Map<string, number>();

  return Object.keys(spec.paths ?? {})
    .sort()
    .map((apiPath) => ({
      apiPath,
      moduleName: getModuleName(apiPath),
      name: uniqueName(toEndpointName(apiPath), endpointNames),
      params: [...apiPath.matchAll(/\{([^}]+)\}/g)].flatMap((match) => (match[1] ? [match[1]] : [])),
      methods: Object.keys(spec.paths?.[apiPath] ?? {}).filter((method) =>
        ["get", "post", "put", "patch", "delete"].includes(method),
      ),
    }));
}

function toEndpointName(apiPath: string): string {
  const parts = apiPath
    .replace(/^\//, "")
    .split("/")
    .map((part) => part.replace(/[{}]/g, ""))
    .filter(Boolean);

  return parts
    .map((part) =>
      part
        .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
        .replace(/[^a-zA-Z0-9]+/g, "_")
        .replace(/^_+|_+$/g, "")
        .toUpperCase(),
    )
    .join("_");
}

function uniqueName(name: string, seen: Map<string, number>): string {
  const count = seen.get(name) ?? 0;
  seen.set(name, count + 1);
  return count === 0 ? name : `${name}_${count + 1}`;
}

function getModuleName(apiPath: string): string {
  return apiPath.split("/").filter(Boolean)[0] ?? "shared";
}

function getSchemaModuleName(schemaName: string): string {
  if (/^(Register|Login|Session|Refresh|Logout|SendOtp|VerifyOtp)/.test(schemaName)) return "auth";
  if (/^Product/.test(schemaName)) return "products";
  if (/^(Cart|AddToCart|ApplyCoupon)/.test(schemaName)) return "cart";
  if (/^(Order|CreateOrder)/.test(schemaName)) return "orders";
  return "shared";
}

function groupBy<T>(items: T[], getKey: (item: T) => string): Map<string, T[]> {
  const groups = new Map<string, T[]>();
  for (const item of items) {
    const key = getKey(item);
    groups.set(key, [...(groups.get(key) ?? []), item]);
  }
  return groups;
}

function toPascalCase(value: string): string {
  return value
    .toLowerCase()
    .split("_")
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("");
}
